[project]
requires-python = ">=3.12"
dependencies = [
    "ruff~=0.5.1",
    "webtypy~=0.1.7",
    "micropip~=0.6.0",
    "pyodide-py~=0.26.1",
    "promplate-pyodide~=0.0.3.3",
    "pre-commit~=3.7.1",
]

[tool.pdm]
distribution = false

[tool.pdm.scripts]
post_install = "pre-commit install"
fmt = { composite = ["ruff check --fix --exit-zero", "ruff format"] }

[tool.black]
line-length = 200

[tool.isort]
profile = "black"
known_first_party = ["__main__"]

[tool.ruff]
line-length = 200

[tool.ruff.lint]
select = [
    # isort
    "I",
    # pep8-naming
    "N",
    # pyflakes
    "F",
    # pycodestyle
    "E",
    "W",
    # ruff
    "RUF",
]
ignore = [
    # Failed to parse pyproject.toml: missing field `name`
    "RUF200",
    # Module level import not at top of file
    "E402",
    "F402",
    # `... import *` used; unable to detect undefined names
    "F403",
    # `await` statement outside of a function
    "F704",
]

[tool.pyright]
reportMissingModuleSource = false
reportWildcardImportFromLibrary = false
