name: eslint check

on: [push, pull_request, workflow_dispatch]

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install modules
        run: bun install
      - name: Run ESLint
        run: bun lint
