name: python checks

on: [push, pull_request, workflow_dispatch]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        env:
          UV_SYSTEM_PYTHON: true
        run: |
          pip install uv --disable-pip-version-check
          uv pip install pdm isort black --compile-bytecode
          pdm export --pyproject | uv pip install -r -
          yarn global add pyright
      - name: Run isort check
        run: |
          python -m isort . --check --diff
      - name: Run black check
        run: |
          python -m black . --check --diff
      - name: Run Ruff check
        run: |
          ruff check --output-format github
          ruff format --check --diff
      - name: Run pyright check
        run: |
          pyright
