name: python checks

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install promplate-pyodide isort black ruff pyodide-py
          yarn global add pyright
      - name: Run isort check
        run: |
          isort . --check --diff
      - name: Run black check
        run: |
          black . --check --diff
      - name: Run Ruff check
        run: |
          ruff check --output-format github
          ruff format --check --diff
      - name: Run pyright check
        run: |
          pyright
